# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe -march=alderlake"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j4 -l4"

# emerge default
EMERGE_DEFAULT_OPTS="--jobs=4 --load-average=4 --getbinpkg"

# fitur
FEATURES="getbinpkg binpkg-request-signature ccache parallel-install candy"

# license
ACCEPT_LICENSE="*"

# Use
USE="-X -systemd -pulseaudio wayland pipewire alsa networkmanager elogind"

# format
BINPKG_FORMAT="gpkg"

# video card
VIDEO_CARDS="intel"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=en_US.UTF-8
