# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe -march=alderlake"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j7 -l8"
CCACHE_DIR="/var/tmp/ccache"

# CC CPP CXX
CC="clang"
CXX="clang++"
CPP="clang-cpp"

# mold
LDFLAGS="-Wl,-O2 -Wl,--as-needed -fuse-ld=mold"

# Default sbctl key locations
MODULES_SIGN_KEY="/var/lib/sbctl/keys/db/db.key"
MODULES_SIGN_CERT="/var/lib/sbctl/keys/db/db.pem"
SECUREBOOT_SIGN_KEY="/var/lib/sbctl/keys/db/db.key"
SECUREBOOT_SIGN_CERT="/var/lib/sbctl/keys/db/db.pem"

# grub
GRUB_PLATFORMS="efi-64"

# emerge default
EMERGE_DEFAULT_OPTS="--jobs=2 --load-average=8 --getbinpkg"

# fitur
FEATURES="getbinpkg binpkg-request-signature ccache parallel-install candy"

# license
ACCEPT_LICENSE="*"

# Use
USE="-systemd -gnome -kde pulseaudio X wayland pipewire alsa networkmanager elogind secureboot modules-sign vaapi"

# format
BINPKG_FORMAT="gpkg"

# video card
VIDEO_CARDS="intel"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=en_US.UTF-8

# Gentoo Mirror
GENTOO_MIRRORS="https://sg.mirrors.cicku.me/gentoo/ \
    https://mirror.freedif.org/gentoo \
    https://enceladus.sg.ext.planetunix.net/pub/gentoo/"
